[package]
name = "intuigram-tui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
compio-term.workspace = true
intuigram-app.workspace = true
crossterm = { workspace = true, features = ["bracketed-paste"] }
futures-util.workspace = true
flume.workspace = true
qrcode = { version = "0.14.1", default-features = false }
ratatui.workspace = true
rasterm.workspace = true
snafu.workspace = true
time.workspace = true

[dev-dependencies]
image = { workspace = true, features = ["png"] }

[lints]
workspace = true
