[package]
name = "intuigram-tui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
compio = { workspace = true, features = ["term"] }
intuigram-lib.workspace = true
crossterm = { workspace = true, features = ["bracketed-paste"] }
futures-util.workspace = true
flume.workspace = true
qrcode.workspace = true
ratatui.workspace = true
rasterm.workspace = true
snafu.workspace = true
time.workspace = true

[dev-dependencies]
image = { workspace = true, features = ["png"] }
vt100.workspace = true

[lints]
workspace = true
