[package]
name = "popgram-store"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
refinery = { workspace = true, features = ["rusqlite"] }
rusqlite = { workspace = true, features = ["backup", "bundled"] }
rustix = { workspace = true, features = ["fs"] }
snafu.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
