[package]
name = "intuigram-config"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
figment = { workspace = true, features = ["env", "json", "toml", "yaml"] }
serde = { workspace = true, features = ["derive"] }
snafu.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
