[package]
name = "compio-mtproto"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
aes.workspace = true
base64.workspace = true
compio = { workspace = true, features = ["io", "net", "runtime", "time"] }
ctr.workspace = true
futures-util.workspace = true
getrandom.workspace = true
grammers-crypto.workspace = true
grammers-mtproto.workspace = true
grammers-tl-types.workspace = true
num-bigint.workspace = true
sha1.workspace = true
sha2.workspace = true
snafu.workspace = true

[lints]
workspace = true
