[package]
name = "intuigram"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-channel.workspace = true
compio = { version = "0.19.1", default-features = false, features = ["runtime"] }
dirs.workspace = true
futures-lite.workspace = true
intuigram-app = { path = "../intuigram-app" }
intuigram-config = { path = "../intuigram-config" }
intuigram-store = { path = "../intuigram-store" }
intuigram-telegram = { path = "../intuigram-telegram" }
intuigram-tui = { path = "../intuigram-tui" }
rpassword.workspace = true
snafu.workspace = true

[lints]
workspace = true
