use std::collections::{HashMap, HashSet};

use crate::domain::*;
use crate::history::{RefreshScope, reconcile_refresh};
use crate::protocol::*;

mod account_management;
mod action;
mod avatar_loads;
mod bootstrap;
mod chat_reconciliation;
mod click_activation;
mod composer;
mod editing;
mod folder;
mod history;
mod input;
mod interface;
mod link_media;
mod location;
mod media_preview;
mod message_selection;
mod messaging;
mod offline_media;
mod outbox;
mod pinned;
mod poll;
mod reconnection;
mod rich_media;
mod saved_dialog_navigation;
mod scheduled;
mod specialized_content;
mod state;
mod topic_navigation;
mod unread;

use action::move_index;
use avatar_loads::AvatarLoads;
use history::HistoryLoads;
use media_preview::{MediaPreviewLoads, PreviewKey};
use offline_media::OfflineMedia;
pub use state::App;
use state::{HistoryKey, PendingDraft, PendingPoll};
