[package]
name = "compio-actor"
version = "0.1.0"
description = "Actors for Compio"
categories = ["asynchronous", "concurrency"]
keywords = ["actor", "async", "compio"]
readme = "README.md"
edition = "2024"
license = "MIT"
repository = "https://github.com/compio-rs/compio-actor"

[dependencies]
compio-dispatcher = "0.11.0"
flume = { version = "0.12.0", default-features = false, features = ["async"] }
futures-channel = "0.3.33"
futures-util = "0.3.33"
snafu.workspace = true

[dev-dependencies]
compio-runtime = "0.12.3"

[lints]
workspace = true
