[package]
name = "compio-term"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
compio = { workspace = true, features = ["runtime"] }
crossterm.workspace = true
futures-util.workspace = true
signal-hook.workspace = true

[target.'cfg(windows)'.dependencies]
crossterm_winapi.workspace = true
windows-sys = { workspace = true, features = [
  "Win32_Foundation",
  "Win32_Security",
  "Win32_System_IO",
  "Win32_System_Threading",
] }

[lints.rust]
unsafe_code = "allow"

[lints.clippy]
missing_errors_doc = "allow"
module_name_repetitions = "allow"
