[package]
name = "intuigram-store"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
refinery = { workspace = true, features = ["rusqlite"] }
rusqlite = { workspace = true, features = ["backup"] }
rustix = { workspace = true, features = ["fs"] }
snafu.workspace = true
sha2.workspace = true
zeroize.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
