[package]
name = "intuigram-media"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
compio = { workspace = true, features = ["fs", "io", "process"] }
image.workspace = true
intuigram-lib.workspace = true
snafu.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
