[package]
name = "intuigram-media"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
compio = { workspace = true, features = ["fs", "process"] }
compio-io.workspace = true
image.workspace = true
intuigram-app.workspace = true
snafu.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
